### ISSUE TITLE
Consider renaming Jackson extension jar as `jackson-datatype-tinytypes`

### ISSUE THREAD

**Issue by cowtowncoder** [caligin/tinytypes#1]
Very interesting project, just found it. Will be interested in learning more.

One thing that may make sense would be to follow convention of Jackson extension modules, for Jackson-handling part: for extensions that add handlers for 3rd party data, prefix "jackson-datatype-" is used. This is not necessary for functioning or anything, but can make it easier for developers to have an idea of what various extensions do, as there are other kinds of extensions as well (for data formats other than json, and so forth).

I also added a link to this project from https://github.com/FasterXML/jackson which hopefully help potential users to find this project.

**Comment by caligin** [comment]
Thanks a lot for the pointer & support!
I'll delve deeper in Jackson's conventions in the next few days -- being in line with the standard would be great.

**Comment by cowtowncoder** [comment]
@caligin Sounds good! As I said, there is no strict technical requirement to have to do that from Jackson side, but users may find it useful (and perhaps some automated tools as well).

**Comment by caligin** [comment]
Are eb0509a and 30b4042 what you meant? I looked around the Jackson wiki but I couldn't find anything else about module conventions.

**Comment by cowtowncoder** [comment]
Yes, that looks good to me.
